"""Catalog of EyeFlow metrics to implement in the Python rewrite."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class MetricItem:
    name: str
    description: str
    source: str


@dataclass(frozen=True, slots=True)
class MetricGroup:
    title: str
    description: str
    items: tuple[MetricItem, ...]


METRIC_GROUPS: tuple[MetricGroup, ...] = (
    MetricGroup(
        title="Meta and Calibration",
        description="Run metadata and acquisition-derived signals needed by downstream analysis.",
        items=(
            MetricItem("NumFrames", "Number of frames processed.", "ReporterClass.m"),
            MetricItem("FrameRate", "Effective frame rate used for analysis.", "ReporterClass.m"),
            MetricItem("InterFramePeriod", "Time spacing between frames.", "ReporterClass.m"),
            MetricItem("UnixTimestampFirst", "First acquisition timestamp in us.", "ReporterClass.m"),
            MetricItem("UnixTimestampLast", "Last acquisition timestamp in us.", "ReporterClass.m"),
            MetricItem("Time", "Time axis used by pulse and waveform analysis.", "pulseAnalysis.m"),
            MetricItem("Frequency", "Frequency axis for transfer-function analysis.", "arterial_venous_correlation.m"),
            MetricItem("PredictedEyeSide", "Predicted eye side metadata.", "predictEyeSide.m"),
            MetricItem("PapillaRatio", "Optic disc size ratio used for calibration.", "AnalyzerClass.m"),
            MetricItem("PapillaXY", "Optic disc center in pixels.", "AnalyzerClass.m"),
        ),
    ),
    MetricGroup(
        title="Mask and QC Metrics",
        description="Mask counts and segmentation-quality indicators that should still be tracked in the Python pipeline.",
        items=(
            MetricItem("QualityControlScoreMaskArtery", "Quality score for artery mask.", "AnalyzerClass.m"),
            MetricItem("QualityControlScoreMaskVein", "Quality score for vein mask.", "AnalyzerClass.m"),
            MetricItem("ArteryNbPxl", "Total artery mask pixel count.", "createMasks.m"),
            MetricItem("VeinNbPxl", "Total vein mask pixel count.", "createMasks.m"),
            MetricItem("RemainingNbPxl", "Pixel count not assigned to artery or vein.", "createMasks.m"),
            MetricItem("ArterySelNbPxl", "Artery pixels inside the selected analysis section.", "bloodFlowVelocity.m"),
            MetricItem("VeinSelNbPxl", "Vein pixels inside the selected analysis section.", "bloodFlowVelocity.m"),
            MetricItem("RemainingSelNbPxl", "Unassigned pixels inside the selected analysis section.", "bloodFlowVelocity.m"),
            MetricItem("QualityControlDiceArtery", "Artery Dice score when a target mask is available.", "segmentationScores.m"),
            MetricItem("QualityControlDiceVein", "Vein Dice score when a target mask is available.", "segmentationScores.m"),
            MetricItem("QualityControlJaccardArtery", "Artery Jaccard score.", "segmentationScores.m"),
            MetricItem("QualityControlJaccardVein", "Vein Jaccard score.", "segmentationScores.m"),
            MetricItem("QualityControlAccuracyArtery", "Artery accuracy score.", "segmentationScores.m"),
            MetricItem("QualityControlAccuracyVein", "Vein accuracy score.", "segmentationScores.m"),
            MetricItem("QualityControlPrecisionArtery", "Artery precision score.", "segmentationScores.m"),
            MetricItem("QualityControlPrecisionVein", "Vein precision score.", "segmentationScores.m"),
        ),
    ),
    MetricGroup(
        title="Velocity and Flow Summary",
        description="Top-level artery and vein velocity and flow summaries derived from the pulse-analysis stage.",
        items=(
            MetricItem("ArterialVelocity", "Mean artery velocity signal over time.", "pulseAnalysis.m"),
            MetricItem("VenousVelocity", "Mean vein velocity signal over time.", "pulseAnalysis.m"),
            MetricItem("ArteryVelocityMean", "Mean artery velocity scalar.", "ArterialResistivityIndex.m"),
            MetricItem("ArteryVelocityMax", "Maximum artery velocity scalar.", "ArterialResistivityIndex.m"),
            MetricItem("ArteryVelocityMin", "Minimum artery velocity scalar.", "ArterialResistivityIndex.m"),
            MetricItem("VeinVelocityMean", "Mean vein velocity scalar.", "ArterialResistivityIndex.m"),
            MetricItem("VeinVelocityMax", "Maximum vein velocity scalar.", "ArterialResistivityIndex.m"),
            MetricItem("VeinVelocityMin", "Minimum vein velocity scalar.", "ArterialResistivityIndex.m"),
            MetricItem("ArteryFlowRateMean", "Mean artery flow-rate scalar.", "ArterialResistivityIndex.m"),
            MetricItem("ArteryFlowRateMax", "Maximum artery flow-rate scalar.", "ArterialResistivityIndex.m"),
            MetricItem("ArteryFlowRateMin", "Minimum artery flow-rate scalar.", "ArterialResistivityIndex.m"),
            MetricItem("VeinFlowRateMean", "Mean vein flow-rate scalar.", "ArterialResistivityIndex.m"),
            MetricItem("VeinFlowRateMax", "Maximum vein flow-rate scalar.", "ArterialResistivityIndex.m"),
            MetricItem("VeinFlowRateMin", "Minimum vein flow-rate scalar.", "ArterialResistivityIndex.m"),
            MetricItem("ArteryResistivityIndexVelocity", "Artery resistivity index from velocity.", "ArterialResistivityIndex.m"),
            MetricItem("ArteryPulsatilityIndexVelocity", "Artery pulsatility index from velocity.", "ArterialResistivityIndex.m"),
            MetricItem("ArteryMaxMinRatioVelocity", "Artery max/min ratio from velocity.", "ArterialResistivityIndex.m"),
            MetricItem("VeinResistivityIndexVelocity", "Vein resistivity index from velocity.", "ArterialResistivityIndex.m"),
            MetricItem("VeinPulsatilityIndexVelocity", "Vein pulsatility index from velocity.", "ArterialResistivityIndex.m"),
            MetricItem("VeinMaxMinRatioVelocity", "Vein max/min ratio from velocity.", "ArterialResistivityIndex.m"),
            MetricItem("ArteryResistivityIndexFlowRate", "Artery resistivity index from flow rate.", "ArterialResistivityIndex.m"),
            MetricItem("ArteryPulsatilityIndexFlowRate", "Artery pulsatility index from flow rate.", "ArterialResistivityIndex.m"),
            MetricItem("ArteryMaxMinRatioFlowRate", "Artery max/min ratio from flow rate.", "ArterialResistivityIndex.m"),
            MetricItem("VeinResistivityIndexFlowRate", "Vein resistivity index from flow rate.", "ArterialResistivityIndex.m"),
            MetricItem("VeinPulsatilityIndexFlowRate", "Vein pulsatility index from flow rate.", "ArterialResistivityIndex.m"),
            MetricItem("VeinMaxMinRatioFlowRate", "Vein max/min ratio from flow rate.", "ArterialResistivityIndex.m"),
        ),
    ),
    MetricGroup(
        title="Velocity Statistics by Section",
        description="Distributional velocity summaries over the selected vessel sections.",
        items=(
            MetricItem("ArteryVelocityMeanSection", "Mean artery velocity in section.", "VelocityStatisticalOutputs.m"),
            MetricItem("ArteryVelocityMaxSection", "Max artery velocity in section.", "VelocityStatisticalOutputs.m"),
            MetricItem("ArteryVelocityMinSection", "Min artery velocity in section.", "VelocityStatisticalOutputs.m"),
            MetricItem("ArteryVelocityModeSection", "Mode artery velocity in section.", "VelocityStatisticalOutputs.m"),
            MetricItem("ArteryVelocityMedianSection", "Median artery velocity in section.", "VelocityStatisticalOutputs.m"),
            MetricItem("ArteryVelocity25Percentile", "25th percentile artery velocity.", "VelocityStatisticalOutputs.m"),
            MetricItem("ArteryVelocity75Percentile", "75th percentile artery velocity.", "VelocityStatisticalOutputs.m"),
            MetricItem("ArteryVelocityMeanTrimmed", "Trimmed mean artery velocity.", "VelocityStatisticalOutputs.m"),
            MetricItem("ArteryVelocityMedianTrimmed", "Trimmed median artery velocity.", "VelocityStatisticalOutputs.m"),
            MetricItem("ArteryVelocityModeTrimmed", "Trimmed mode artery velocity.", "VelocityStatisticalOutputs.m"),
            MetricItem("VeinVelocityMeanSection", "Mean vein velocity in section.", "VelocityStatisticalOutputs.m"),
            MetricItem("VeinVelocityMaxSection", "Max vein velocity in section.", "VelocityStatisticalOutputs.m"),
            MetricItem("VeinVelocityMinSection", "Min vein velocity in section.", "VelocityStatisticalOutputs.m"),
            MetricItem("VeinVelocityModeSection", "Mode vein velocity in section.", "VelocityStatisticalOutputs.m"),
            MetricItem("VeinVelocityMedianSection", "Median vein velocity in section.", "VelocityStatisticalOutputs.m"),
            MetricItem("VeinVelocity25Percentile", "25th percentile vein velocity.", "VelocityStatisticalOutputs.m"),
            MetricItem("VeinVelocity75Percentile", "75th percentile vein velocity.", "VelocityStatisticalOutputs.m"),
            MetricItem("VeinVelocityMeanTrimmed", "Trimmed mean vein velocity.", "VelocityStatisticalOutputs.m"),
            MetricItem("VeinVelocityMedianTrimmed", "Trimmed median vein velocity.", "VelocityStatisticalOutputs.m"),
            MetricItem("VeinVelocityModeTrimmed", "Trimmed mode vein velocity.", "VelocityStatisticalOutputs.m"),
            MetricItem("ArteryHistogramBybranches", "Velocity histogram per artery branch.", "VelocityHistogram.m"),
            MetricItem("VeinHistogramBybranches", "Velocity histogram per vein branch.", "VelocityHistogram.m"),
        ),
    ),
    MetricGroup(
        title="Waveform Metrics",
        description="Cardiac waveform, Fourier, and notch-related outputs derived from artery and vein signals.",
        items=(
            MetricItem("HeartBeat", "Heartbeat estimate in bpm.", "pulseAnalysis.m"),
            MetricItem("HeartBeatFFT", "Heartbeat estimate from FFT.", "SpectralWaveformAnalysis.m"),
            MetricItem("SystoleIndices", "Detected systolic frame indices.", "pulseAnalysis.m"),
            MetricItem("ArterySystoleMaxIndices", "Indices of artery systolic maxima.", "pulseAnalysis.m"),
            MetricItem("ArteryDiastoleMinIndices", "Indices of artery diastolic minima.", "pulseAnalysis.m"),
            MetricItem("sysIdxList", "Systolic acceleration peak indices.", "pulseAnalysis.m"),
            MetricItem("ArteryTimeToMaxIncrease", "Time to maximal artery upstroke.", "pulseAnalysis.m"),
            MetricItem("ArteryTimeToPeakSystole", "Time to artery systolic peak.", "pulseAnalysis.m"),
            MetricItem("ArteryTimeToMinDiastole", "Time to artery minimum diastole.", "pulseAnalysis.m"),
            MetricItem("ArteryTimeToPeakSystoleFromDiastole", "Time from minimum diastole to peak systole.", "pulseAnalysis.m"),
            MetricItem("ArteryTimeToDescent", "Time from peak toward descent.", "pulseAnalysis.m"),
            MetricItem("ArteryTimePeakToDescent", "Time from peak to descent reference.", "pulseAnalysis.m"),
            MetricItem("ArterialPeakFrequencies", "Dominant artery waveform frequencies.", "ArterialWaveformAnalysis.m"),
            MetricItem("ArterialFourierAmplitude", "Artery waveform Fourier amplitudes.", "ArterialWaveformAnalysis.m"),
            MetricItem("ArterialFourierPhase", "Artery waveform Fourier phases.", "ArterialWaveformAnalysis.m"),
            MetricItem("VenousPeakFrequencies", "Dominant vein waveform frequencies.", "VenousWaveformAnalysis.m"),
            MetricItem("VenousFourierAmplitude", "Vein waveform Fourier amplitudes.", "VenousWaveformAnalysis.m"),
            MetricItem("VenousFourierPhase", "Vein waveform Fourier phases.", "VenousWaveformAnalysis.m"),
            MetricItem("DicroticNotchVisibility", "Visibility score for the dicrotic notch.", "ArterialWaveformAnalysis.m"),
            MetricItem("SystoleDuration", "Duration of systole.", "ArterialWaveformAnalysis.m"),
            MetricItem("DiastoleDuration", "Duration of diastole.", "ArterialWaveformAnalysis.m"),
            MetricItem("SystolicUpstroke", "Arterial systolic upstroke metric.", "ArterialWaveformAnalysis.m"),
            MetricItem("SystolicDownstroke", "Arterial systolic downstroke metric.", "ArterialWaveformAnalysis.m"),
            MetricItem("DiastolicUpstroke", "Arterial diastolic upstroke metric.", "ArterialWaveformAnalysis.m"),
            MetricItem("DiastolicRunoff", "Arterial diastolic runoff metric.", "ArterialWaveformAnalysis.m"),
            MetricItem("VeinTimeToPeakFromMin", "Time from venous minimum to venous peak.", "VenousWaveformAnalysis.m"),
        ),
    ),
    MetricGroup(
        title="Artery-Vein Coupling",
        description="Cross-signal transfer and delay metrics between artery and vein signals.",
        items=(
            MetricItem("ArteryVeinPhaseDelay", "Time delay between artery and vein signals.", "arterial_venous_correlation.m"),
            MetricItem("TransFunctionModLog10", "Log-modulus transfer function between artery and vein signals.", "arterial_venous_correlation.m"),
            MetricItem("TransFunctionPhaseDegrees", "Phase transfer function between artery and vein signals.", "arterial_venous_correlation.m"),
            MetricItem("WindkesselPureDelay", "Pure delay term of the Windkessel fit.", "arterial_venous_delay.m"),
            MetricItem("WindkesselDecayRC", "Decay RC term of the Windkessel fit.", "arterial_venous_delay.m"),
            MetricItem("WindkesselCeff", "Effective Windkessel compliance.", "arterial_venous_delay.m"),
            MetricItem("WindkesselReff", "Effective Windkessel resistance.", "arterial_venous_delay.m"),
            MetricItem("TransFunctionModLog10FlowRate", "Transfer modulus between artery and vein flow-rate signals.", "combinedCrossSectionAnalysis.m"),
            MetricItem("TransFunctionPhaseDegreesFlowRate", "Transfer phase between artery and vein flow-rate signals.", "combinedCrossSectionAnalysis.m"),
        ),
    ),
    MetricGroup(
        title="Per-Beat Outputs",
        description="Beat-resolved signals and derived arrays for artery and vein analysis.",
        items=(
            MetricItem("beatPeriodIdx", "Beat period in frame counts.", "perBeatAnalysis.m"),
            MetricItem("beatPeriodSeconds", "Beat period in seconds.", "perBeatAnalysis.m"),
            MetricItem("<Artery|Vein>_VelocitySignalPerBeat", "Velocity signal split by beat.", "perBeatAnalysis.m"),
            MetricItem("<Artery|Vein>_VelocitySignalPerBeatFFT_abs", "Per-beat FFT amplitude.", "perBeatAnalysis.m"),
            MetricItem("<Artery|Vein>_VelocitySignalPerBeatFFT_arg", "Per-beat FFT phase.", "perBeatAnalysis.m"),
            MetricItem("<Artery|Vein>_VelocitySignalPerBeatBandLimited", "Band-limited per-beat velocity signal.", "perBeatAnalysis.m"),
            MetricItem("<Artery|Vein>_VmaxPerBeatBandLimited", "Per-beat max velocity after band limiting.", "perBeatAnalysis.m"),
            MetricItem("<Artery|Vein>_VminPerBeatBandLimited", "Per-beat min velocity after band limiting.", "perBeatAnalysis.m"),
            MetricItem("<Artery|Vein>_VTIPerBeat", "Velocity-time integral per beat.", "perBeatAnalysis.m"),
        ),
    ),
    MetricGroup(
        title="Pulse Wave Velocity",
        description="Flexural pulse-wave outputs computed along artery and vein branches.",
        items=(
            MetricItem("<artery|vein>_PWV_Segments_Labels", "Branch labels used for pulse-wave velocity.", "pulseVelocity.m"),
            MetricItem("ArteryPulseWaveVelocities", "Artery pulse-wave velocities.", "pulseVelocity.m"),
            MetricItem("VeinPulseWaveVelocities", "Vein pulse-wave velocities.", "pulseVelocity.m"),
            MetricItem("ArteryPulseWaveVelocitiesWavelengths", "Artery pulse-wave wavelengths.", "pulseVelocity.m"),
            MetricItem("VeinPulseWaveVelocitiesWavelengths", "Vein pulse-wave wavelengths.", "pulseVelocity.m"),
        ),
    ),
    MetricGroup(
        title="Cross-Section Flow and Diameter",
        description="Scalar cross-section metrics for diameters, volume rates, and cycle fractions.",
        items=(
            MetricItem("ArterialVolumeRate", "Artery volume-rate signal over time.", "exportCrossSectionResults.m"),
            MetricItem("VenousVolumeRate", "Vein volume-rate signal over time.", "exportCrossSectionResults.m"),
            MetricItem("ArteryVolumeRateSystole", "Mean systolic artery volume rate.", "strokeAndTotalVolume.m"),
            MetricItem("ArteryVolumeRateDiastole", "Mean diastolic artery volume rate.", "strokeAndTotalVolume.m"),
            MetricItem("VeinVolumeRateSystole", "Mean systolic vein volume rate.", "strokeAndTotalVolume.m"),
            MetricItem("VeinVolumeRateDiastole", "Mean diastolic vein volume rate.", "strokeAndTotalVolume.m"),
            MetricItem("ArteryVolumeRateSystolethird", "Artery volume rate over systolic third.", "strokeAndTotalVolume.m"),
            MetricItem("ArteryVolumeRateDiastoletwothird", "Artery volume rate over diastolic two-thirds.", "strokeAndTotalVolume.m"),
            MetricItem("VeinVolumeRateSystolethird", "Vein volume rate over systolic third.", "strokeAndTotalVolume.m"),
            MetricItem("VeinVolumeRateDiastoletwothird", "Vein volume rate over diastolic two-thirds.", "strokeAndTotalVolume.m"),
            MetricItem("ArteryCycleVolume", "Total artery cycle volume.", "strokeAndTotalVolume.m"),
            MetricItem("ArterySystolicFraction", "Artery systolic fraction of cycle volume.", "strokeAndTotalVolume.m"),
            MetricItem("ArteryDiastolicFraction", "Artery diastolic fraction of cycle volume.", "strokeAndTotalVolume.m"),
            MetricItem("VeinCycleVolume", "Total vein cycle volume.", "strokeAndTotalVolume.m"),
            MetricItem("VeinSystolicFraction", "Vein systolic fraction of cycle volume.", "strokeAndTotalVolume.m"),
            MetricItem("VeinDiastolicFraction", "Vein diastolic fraction of cycle volume.", "strokeAndTotalVolume.m"),
            MetricItem("ArteryDiameterMean", "Mean artery diameter across valid sections.", "widthHistogram.m"),
            MetricItem("ArteryDiameterMedian", "Median artery diameter across valid sections.", "widthHistogram.m"),
            MetricItem("ArteryDiameterSpread", "Spread of artery diameters.", "widthHistogram.m"),
            MetricItem("ArteryValidSectionCount", "Count of valid artery sections.", "widthHistogram.m"),
            MetricItem("ArteryTotalSectionCount", "Total count of artery sections.", "widthHistogram.m"),
            MetricItem("VeinDiameterMean", "Mean vein diameter across valid sections.", "widthHistogram.m"),
            MetricItem("VeinDiameterMedian", "Median vein diameter across valid sections.", "widthHistogram.m"),
            MetricItem("VeinDiameterSpread", "Spread of vein diameters.", "widthHistogram.m"),
            MetricItem("VeinValidSectionCount", "Count of valid vein sections.", "widthHistogram.m"),
            MetricItem("VeinTotalSectionCount", "Total count of vein sections.", "widthHistogram.m"),
        ),
    ),
    MetricGroup(
        title="Cross-Section Profiles and Segments",
        description="Structured arrays exported per branch, per circle, and per beat for cross-section analysis.",
        items=(
            MetricItem("displacementField_profile_<Artery|Vein>", "Displacement-field profile arrays.", "generateCrossSectionSignals.m"),
            MetricItem("displacementField_profile_D_x1_<Artery|Vein>", "First displacement derivative along x1.", "generateCrossSectionSignals.m"),
            MetricItem("displacementField_profile_D_x2_<Artery|Vein>", "First displacement derivative along x2.", "generateCrossSectionSignals.m"),
            MetricItem("displacementField_profile_fft_x1_<Artery|Vein>", "FFT of displacement profile along x1.", "generateCrossSectionSignals.m"),
            MetricItem("displacementField_profile_fft_x2_<Artery|Vein>", "FFT of displacement profile along x2.", "generateCrossSectionSignals.m"),
            MetricItem("displacementField_D1_<Artery|Vein>", "Cardiac-frequency displacement component.", "generateCrossSectionSignals.m"),
            MetricItem("displacementField_D_x1_stats_<Artery|Vein>", "Statistics for displacement derivative x1.", "generateCrossSectionSignals.m"),
            MetricItem("displacementField_D_x2_stats_<Artery|Vein>", "Statistics for displacement derivative x2.", "generateCrossSectionSignals.m"),
            MetricItem("displacementField_D1_x1_stats_<Artery|Vein>", "Statistics for D1 derivative x1.", "generateCrossSectionSignals.m"),
            MetricItem("displacementField_D1_x2_stats_<Artery|Vein>", "Statistics for D1 derivative x2.", "generateCrossSectionSignals.m"),
            MetricItem("velocitySignalPerBeatPerSegmentWhole<Artery|Vein>", "Per-segment per-beat velocity signal over full cycles.", "exportProfilesToH5.m"),
            MetricItem("velocitySignalPerBeatPerSegmentWholeFFT_abs<Artery|Vein>", "FFT amplitude of full-cycle segment signals.", "exportProfilesToH5.m"),
            MetricItem("velocitySignalPerBeatPerSegmentWholeFFT_arg<Artery|Vein>", "FFT phase of full-cycle segment signals.", "exportProfilesToH5.m"),
            MetricItem("velocitySignalPerBeatPerSegmentWholeBandLimited<Artery|Vein>", "Band-limited full-cycle segment signals.", "exportProfilesToH5.m"),
            MetricItem("velocitySignalPerBeatPerSegmentTrunc<Artery|Vein>", "Per-segment per-beat velocity signal over truncated cycles.", "exportProfilesToH5.m"),
            MetricItem("velocitySignalPerBeatPerSegmentTruncFFT_abs<Artery|Vein>", "FFT amplitude of truncated segment signals.", "exportProfilesToH5.m"),
            MetricItem("velocitySignalPerBeatPerSegmentTruncFFT_arg<Artery|Vein>", "FFT phase of truncated segment signals.", "exportProfilesToH5.m"),
            MetricItem("velocitySignalPerBeatPerSegmentTruncBandLimited<Artery|Vein>", "Band-limited truncated segment signals.", "exportProfilesToH5.m"),
            MetricItem("VelocitySignalPerBeatPerSegment<Artery|Vein>", "Per-segment beat-aligned velocity signal.", "exportProfilesToH5.m"),
            MetricItem("VelocitySignalPerBeatPerSegmentFFT_abs<Artery|Vein>", "FFT amplitude of beat-aligned segment signals.", "exportProfilesToH5.m"),
            MetricItem("VelocitySignalPerBeatPerSegmentFFT_arg<Artery|Vein>", "FFT phase of beat-aligned segment signals.", "exportProfilesToH5.m"),
            MetricItem("VelocitySignalPerBeatPerSegmentBandLimited<Artery|Vein>", "Band-limited beat-aligned segment signals.", "exportProfilesToH5.m"),
            MetricItem("velocity_seg_mean_<Artery|Vein>", "Mean velocity per branch and circle.", "exportProfilesToH5.m"),
            MetricItem("VelocityProfileSeg<Artery|Vein>", "Velocity profiles per segment.", "exportProfilesToH5.m"),
            MetricItem("VelocityProfilesSegInterpOneBeat<Artery|Vein>", "Interpolated one-beat velocity profiles.", "profilePatchWomersley.m"),
            MetricItem("<artery|vein>_Segments_Labels", "Segment labels exported to H5.", "exportSegmentsValueToH5.m"),
        ),
    ),
    MetricGroup(
        title="Womersley and Harmonic Templates",
        description="Template outputs produced by the advanced Womersley fit and harmonic decomposition code paths.",
        items=(
            MetricItem("<var_name>_mu_<Artery|Vein>", "Womersley fit mu parameter.", "exportProfilesToH5.m"),
            MetricItem("<var_name>_a_<Artery|Vein>", "Womersley fit a parameter.", "exportProfilesToH5.m"),
            MetricItem("<var_name>_u_<Artery|Vein>", "Womersley fit u parameter.", "exportProfilesToH5.m"),
            MetricItem("<var_name>_wc_<Artery|Vein>", "Womersley fit wc parameter.", "exportProfilesToH5.m"),
            MetricItem("<var_name>_w_<Artery|Vein>", "Womersley fit w parameter.", "exportProfilesToH5.m"),
            MetricItem("<var_name>_validMask_<Artery|Vein>", "Validity mask for fitted segments.", "exportProfilesToH5.m"),
            MetricItem("<var_name>_s_<Artery|Vein>", "Womersley fit quality or scale term.", "exportProfilesToH5.m"),
            MetricItem("<field>_r", "Real part of harmonic field output.", "profilePatchWomersley.m"),
            MetricItem("<field>_i", "Imaginary part of harmonic field output.", "profilePatchWomersley.m"),
            MetricItem("<field>", "Direct harmonic field output when not split into real/imag parts.", "profilePatchWomersley.m"),
        ),
    ),
)


def iter_metrics() -> tuple[MetricItem, ...]:
    """Flatten the metric groups into a single tuple."""

    return tuple(item for group in METRIC_GROUPS for item in group.items)
