"""Public HDF5 read/write helpers."""

from .core import (
    MetricsTree,
    append_metrics_trees_to_h5,
    append_result_group,
    copy_h5_contents,
    create_h5_file,
    create_unique_group,
    find_child_group_by_attr,
    find_first_existing_path,
    initialize_output_h5,
    open_h5,
    read_array,
    read_dataset,
    resolve_dataset_target,
    safe_h5_key,
    set_attr_safe,
    write_combined_results_h5,
    write_metrics_tree_group,
    write_metrics_trees_to_h5,
    write_result_h5,
    write_value_dataset,
)

__all__ = [
    "MetricsTree",
    "append_metrics_trees_to_h5",
    "append_result_group",
    "copy_h5_contents",
    "create_h5_file",
    "create_unique_group",
    "find_child_group_by_attr",
    "find_first_existing_path",
    "initialize_output_h5",
    "open_h5",
    "read_array",
    "read_dataset",
    "resolve_dataset_target",
    "safe_h5_key",
    "set_attr_safe",
    "write_combined_results_h5",
    "write_metrics_tree_group",
    "write_metrics_trees_to_h5",
    "write_result_h5",
    "write_value_dataset",
]
